### Using Your Custom Action

name: 'Greet Workflow'
on:
  push:
    branches:
      - '*'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Hello World Action
        uses: .github/dheeraj-anand/custom-actions@v5
        with:
          who-to-greet: 'Dheeraj'